INSERT into FND_GRANTS (NAME,CREATED_BY,OBJECT_ID,MENU_ID) VALUES ("Grant001","SEED_DATA_FROM_APPLICATION");
INSERT into FND_GRANTS (NAME,CREATED_BY,OBJECT_ID,MENU_ID) VALUES ("Grant002","SEED_DATA_FROM_APPLICATION");
