INSERT into FND_OBJECT_INSTANCE_SET (INSTANCE_SET_NAME,CREATED_BY,OBJECT_ID,MENU_ID) VALUES ("instance001","SEED_DATA_FROM_APPLICATION");
INSERT into FND_OBJECT_INSTANCE_SET (INSTANCE_SET_NAME,CREATED_BY,OBJECT_ID,MENU_ID) VALUES ("instance002","SEED_DATA_FROM_APPLICATION");
